### ISSUE TITLE
Metadata registration issue

### ISSUE THREAD

**Issue by jsalcal** [switchonproject/switchon-tools#4]
I was testing out the data upload tool and metadata registration tool and I encountered an error uploading a simple zipped shapefile (OSM water polygons). 

![image](https://cloud.githubusercontent.com/assets/13152899/26108643/6fed6aea-3a4d-11e7-98d1-f3bd0e352a7a.png)

Representation:

[{"function": "service", "contenttype": "application/xml", "name": "simplified_water_polygons", "protocol": "OGC:WMS-1.1.1-http-get-capabilities", "type": "original data", "contentlocation": "http://dl-ng003.xtr.deltares.nl/geoserver/osm_simplified_water_polygons/wms?service=WMS&version=1.1.0&request=GetCapabilities", "description": "WMS service"}, {"function": "service", "contenttype": "application/xml", "name": "simplified_water_polygons", "protocol": "OGC:WMS-1.1.1-http-get-capabilities", "type": "aggregated data", "contentlocation": "http://dl-ng003.xtr.deltares.nl/geoserver/osm_simplified_water_polygons/wms?service=WMS&version=1.1.0&request=GetCapabilities", "description": "WMS service"}, {"function": "service", "contenttype": "application/xml", "name": "simplified_water_polygons", "protocol": "OGC:WFS-1.0.0-http-get-capabilities", "type": "original data", "contentlocation": "http://dl-ng003.xtr.deltares.nl/geoserver/osm_simplified_water_polygons/ows?service=WFS&version=1.0.0&request=GetCapabilities", "description": "WFS service"}, {"function": "download", "contenttype": "application/zip", "name": "simplified-water-polygons-complete-3857.zip", "uploadmessage": "deriveSpatialIndex:shp", "protocol": "WWW:DOWNLOAD-1.0-http--download", "type": "original data", "contentlocation": "http://dl-ng003.xtr.deltares.nl/data/osm_simplified_water_polygons/simplified-water-polygons-complete-3857.zip", "description": "Zipped shapefile"}]

Do you see what went wrong?
If you need to check the logs it was around this timestamp: 2017-05-16 15:30

**Comment by p-a-s-c-a-l** [comment]
@jsalcal 

I couldn't reproduce the problem. Yesterday, I performed a database upgrade and backup. The problem was probably caused by a db connection issue. Please try again.

In v1.2 (already deployed at http://www.water-switch-on.eu/sip-webclient/odrtool/), I added the possibility to download the incorrect meta-data JSON file, if the registration process fails.

**Comment by jsalcal** [comment]
You are right. I tried again and succeeded. Thanks
